name: Test Build

on:
  push:

jobs:
  test-build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f # v2.0.5

      - name: Set up
        run: |
          rustup default stable
          cargo install --locked cargo-zigbuild
          cargo fetch --locked

      - name: Install Mingw-w64
        run: |
          brew install mingw-w64

      - name: Build with cargo-zigbuild for windows x86_64
        env:
          CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER: x86_64-w64-mingw32-gcc
          CC_x86_64_pc_windows_gnu: x86_64-w64-mingw32-gcc
          CXX_x86_64_pc_windows_gnu: x86_64-w64-mingw32-g++
        run: |
          rustup target add x86_64-pc-windows-gnu
          cargo zigbuild --release --target x86_64-pc-windows-gnu --verbose

      - name: Build with cargo-zigbuild for linux x86_64
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo zigbuild --release --target x86_64-unknown-linux-gnu --verbose

      - name: Build with cargo-zigbuild for linux aarch64
        run: |
          rustup target add aarch64-unknown-linux-gnu
          cargo zigbuild --release --target aarch64-unknown-linux-gnu --verbose

      - name: Build with cargo-zigbuild for macOS x86_64
        env:
          CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER: rust-lld
        run: |
          rustup target add x86_64-apple-darwin
          cargo zigbuild --release --target x86_64-apple-darwin --verbose

      - name: Build with cargo-zigbuild for macOS aarch64
        env:
          CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER: rust-lld
        run: |
          rustup target add aarch64-apple-darwin
          cargo zigbuild --release --target aarch64-apple-darwin --verbose
